"""
Seed data for organizations.
8 organizations: 1 platform, 2 buyers (Indian shipping companies), 5 suppliers.
"""

ORGANIZATIONS = [
    # ── Platform ────────────────────────────────────────────────────────────
    {
        "name": "PortiQ Platform",
        "type": "PLATFORM",
        "slug": "portiq",
        "legal_name": "PortiQ Technologies Pvt Ltd",
        "registration_number": "U72200MH2023PTC123456",
        "address": {
            "line1": "WeWork BKC, G Block",
            "city": "Mumbai",
            "state": "Maharashtra",
            "country": "India",
            "pincode": "400051",
        },
        "primary_email": "admin@portiq.in",
        "primary_phone": "+912226543210",
        "website": "https://portiq.in",
    },
    # ── Buyers ──────────────────────────────────────────────────────────────
    {
        "name": "Great Eastern Shipping",
        "type": "BUYER",
        "slug": "great-eastern",
        "legal_name": "The Great Eastern Shipping Company Ltd",
        "registration_number": "L35110MH1948PLC006367",
        "address": {
            "line1": "Ocean House, 134-A Dr Annie Besant Road, Worli",
            "city": "Mumbai",
            "state": "Maharashtra",
            "country": "India",
            "pincode": "400018",
        },
        "primary_email": "procurement@greateastern.com",
        "primary_phone": "+912224927000",
        "website": "https://www.greateasternshipping.com",
    },
    {
        "name": "Shipping Corporation of India",
        "type": "BUYER",
        "slug": "sci",
        "legal_name": "The Shipping Corporation of India Ltd",
        "registration_number": "L63011MH1950GOI008033",
        "address": {
            "line1": "Shipping House, 245 Madame Cama Road",
            "city": "Mumbai",
            "state": "Maharashtra",
            "country": "India",
            "pincode": "400021",
        },
        "primary_email": "procurement@sci.co.in",
        "primary_phone": "+912222026700",
        "website": "https://www.shipindia.com",
    },
    # ── Suppliers ───────────────────────────────────────────────────────────
    {
        "name": "Ocean Ship Stores",
        "type": "SUPPLIER",
        "slug": "ocean-ship-stores",
        "legal_name": "Ocean Ship Stores Pvt Ltd",
        "registration_number": "U51909MH2015PTC267890",
        "address": {
            "line1": "Plot 14, Sassoon Dock, Colaba",
            "city": "Mumbai",
            "state": "Maharashtra",
            "country": "India",
            "pincode": "400005",
        },
        "primary_email": "info@oceanshipstores.com",
        "primary_phone": "+912222151234",
        "website": "https://www.oceanshipstores.com",
    },
    {
        "name": "Marine Supplies International",
        "type": "SUPPLIER",
        "slug": "marine-supplies-intl",
        "legal_name": "Marine Supplies International Pte Ltd",
        "registration_number": "201512345K",
        "address": {
            "line1": "30 Tuas Crescent",
            "city": "Singapore",
            "state": "Singapore",
            "country": "Singapore",
            "pincode": "638729",
        },
        "primary_email": "sales@marinesupplies.sg",
        "primary_phone": "+6568621234",
        "website": "https://www.marinesupplies.sg",
    },
    {
        "name": "Navkar Ship Chandlers",
        "type": "SUPPLIER",
        "slug": "navkar-chandlers",
        "legal_name": "Navkar Ship Chandlers Pvt Ltd",
        "registration_number": "U51100GJ2010PTC061234",
        "address": {
            "line1": "Shop 7, Port Colony Road, Gandhidham",
            "city": "Kandla",
            "state": "Gujarat",
            "country": "India",
            "pincode": "370201",
        },
        "primary_email": "orders@navkarchandlers.com",
        "primary_phone": "+912836234567",
        "website": "https://www.navkarchandlers.com",
    },
    {
        "name": "Seahawk Marine Supplies",
        "type": "SUPPLIER",
        "slug": "seahawk-marine",
        "legal_name": "Seahawk Marine Supplies Pvt Ltd",
        "registration_number": "U51909TN2018PTC123789",
        "address": {
            "line1": "No. 22, Rajaji Salai, Royapuram",
            "city": "Chennai",
            "state": "Tamil Nadu",
            "country": "India",
            "pincode": "600013",
        },
        "primary_email": "supply@seahawkmarine.com",
        "primary_phone": "+914425951234",
        "website": "https://www.seahawkmarine.com",
    },
    {
        "name": "Bharat Ship Stores",
        "type": "SUPPLIER",
        "slug": "bharat-ship-stores",
        "legal_name": "Bharat Ship Stores Pvt Ltd",
        "registration_number": "U51909AP2012PTC045678",
        "address": {
            "line1": "18-1-45, Port Area, Visakhapatnam Port",
            "city": "Visakhapatnam",
            "state": "Andhra Pradesh",
            "country": "India",
            "pincode": "530035",
        },
        "primary_email": "info@bharatshipstores.com",
        "primary_phone": "+918912567890",
        "website": "https://www.bharatshipstores.com",
    },
]
