"""
Seed data for supplier profiles.
5 supplier profiles linked to supplier organizations by org_slug.
"""

SUPPLIER_PROFILES = [
    {
        "org_slug": "ocean-ship-stores",
        "tier": "PREFERRED",
        "onboarding_status": "APPROVED",
        "company_name": "Ocean Ship Stores",
        "contact_name": "Mohammed Khan",
        "contact_email": "mohammed@oceanshipstores.com",
        "contact_phone": "+919820300001",
        "gst_number": "27AABCO1234A1Z5",
        "pan_number": "AABCO1234A",
        "address_line1": "Plot 14, Sassoon Dock, Colaba",
        "city": "Mumbai",
        "state": "Maharashtra",
        "pincode": "400005",
        "country": "India",
        "categories": ["11", "23", "25", "61", "69", "71", "73"],
        "port_coverage": ["INMAA", "INNSA", "INJNP"],
    },
    {
        "org_slug": "marine-supplies-intl",
        "tier": "PREMIUM",
        "onboarding_status": "APPROVED",
        "company_name": "Marine Supplies International",
        "contact_name": "Chen Wei",
        "contact_email": "chen@marinesupplies.sg",
        "contact_phone": "+6591234567",
        "gst_number": "29AABCM5678B1Z3",
        "pan_number": "AABCM5678B",
        "address_line1": "30 Tuas Crescent",
        "city": "Singapore",
        "state": "Singapore",
        "pincode": "638729",
        "country": "Singapore",
        "categories": ["11", "15", "31", "33", "51", "53", "65", "87"],
        "port_coverage": ["SGSIN", "INKOL", "INMAA"],
    },
    {
        "org_slug": "navkar-chandlers",
        "tier": "VERIFIED",
        "onboarding_status": "APPROVED",
        "company_name": "Navkar Ship Chandlers",
        "contact_name": "Kishore Jain",
        "contact_email": "kishore@navkarchandlers.com",
        "contact_phone": "+919820400001",
        "gst_number": "24AABCN9012C1Z1",
        "pan_number": "AABCN9012C",
        "address_line1": "Shop 7, Port Colony Road, Gandhidham",
        "city": "Kandla",
        "state": "Gujarat",
        "pincode": "370201",
        "country": "India",
        "categories": ["11", "21", "23", "39", "45", "47", "71"],
        "port_coverage": ["INKND", "INMUN", "INJNP"],
    },
    {
        "org_slug": "seahawk-marine",
        "tier": "VERIFIED",
        "onboarding_status": "APPROVED",
        "company_name": "Seahawk Marine Supplies",
        "contact_name": "Lakshmi Iyer",
        "contact_email": "lakshmi@seahawkmarine.com",
        "contact_phone": "+919820500001",
        "gst_number": "33AABCS3456D1Z7",
        "pan_number": "AABCS3456D",
        "address_line1": "No. 22, Rajaji Salai, Royapuram",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "pincode": "600013",
        "country": "India",
        "categories": ["17", "19", "25", "61", "63", "77", "79"],
        "port_coverage": ["INMAA", "INVTZ", "INKOL"],
    },
    {
        "org_slug": "bharat-ship-stores",
        "tier": "BASIC",
        "onboarding_status": "APPROVED",
        "company_name": "Bharat Ship Stores",
        "contact_name": "Ravi Kumar",
        "contact_email": "ravi@bharatshipstores.com",
        "contact_phone": "+919820600001",
        "gst_number": "37AABCB7890E1Z9",
        "pan_number": "AABCB7890E",
        "address_line1": "18-1-45, Port Area, Visakhapatnam Port",
        "city": "Visakhapatnam",
        "state": "Andhra Pradesh",
        "pincode": "530035",
        "country": "India",
        "categories": ["11", "23", "45", "47", "69", "71"],
        "port_coverage": ["INVTZ", "INMAA"],
    },
]
