"""
Seed data for vessels.
8 vessels belonging to 2 buyer organizations (Great Eastern Shipping, SCI).
"""

from decimal import Decimal

VESSELS = [
    {
        "name": "Jag Arnav",
        "imo_number": "9410643",
        "mmsi": "419000001",
        "vessel_type": "BULK_CARRIER",
        "flag_state": "IND",
        "owner_org_slug": "great-eastern",
        "gross_tonnage": Decimal("34591"),
        "crew_size": 25,
        "year_built": 2010,
        "last_known_port": "INMAA",
    },
    {
        "name": "Jag Priya",
        "imo_number": "9525549",
        "mmsi": "419000002",
        "vessel_type": "TANKER",
        "flag_state": "IND",
        "owner_org_slug": "great-eastern",
        "gross_tonnage": Decimal("81297"),
        "crew_size": 32,
        "year_built": 2012,
        "last_known_port": "INNSA",
    },
    {
        "name": "Jag Laadki",
        "imo_number": "9294875",
        "mmsi": "419000003",
        "vessel_type": "TANKER",
        "flag_state": "IND",
        "owner_org_slug": "great-eastern",
        "gross_tonnage": Decimal("57411"),
        "crew_size": 28,
        "year_built": 2006,
        "last_known_port": "INMUN",
    },
    {
        "name": "SCI Yamuna",
        "imo_number": "9250638",
        "mmsi": "419000004",
        "vessel_type": "TANKER",
        "flag_state": "IND",
        "owner_org_slug": "sci",
        "gross_tonnage": Decimal("81076"),
        "crew_size": 30,
        "year_built": 2003,
        "last_known_port": "INJNP",
    },
    {
        "name": "SCI Nalanda",
        "imo_number": "9422855",
        "mmsi": "419000005",
        "vessel_type": "BULK_CARRIER",
        "flag_state": "IND",
        "owner_org_slug": "sci",
        "gross_tonnage": Decimal("32354"),
        "crew_size": 24,
        "year_built": 2010,
        "last_known_port": "INKOL",
    },
    {
        "name": "SCI Rajendra",
        "imo_number": "9250614",
        "mmsi": "419000006",
        "vessel_type": "CONTAINER",
        "flag_state": "IND",
        "owner_org_slug": "sci",
        "gross_tonnage": Decimal("20827"),
        "crew_size": 22,
        "year_built": 2003,
        "last_known_port": "INMAA",
    },
    {
        "name": "SCI Kamet",
        "imo_number": "9421620",
        "mmsi": "419000007",
        "vessel_type": "TANKER",
        "flag_state": "IND",
        "owner_org_slug": "sci",
        "gross_tonnage": Decimal("157833"),
        "crew_size": 35,
        "year_built": 2009,
        "last_known_port": "INNSA",
    },
    {
        "name": "Jag Ravi",
        "imo_number": "9483590",
        "mmsi": "419000008",
        "vessel_type": "CONTAINER",
        "flag_state": "IND",
        "owner_org_slug": "great-eastern",
        "gross_tonnage": Decimal("50723"),
        "crew_size": 26,
        "year_built": 2011,
        "last_known_port": "INVTZ",
    },
]
